graph TD;
genotype-1-->root;
genotype-4-->genotype-1;
genotype-2-->genotype-1;
genotype-11-->genotype-4;
genotype-10-->genotype-11;
genotype-3-->root;
genotype-9-->genotype-1;
genotype-14-->genotype-9;
genotype-8-->genotype-1;
genotype-13-->genotype-10;
genotype-6-->genotype-4;
genotype-7-->root;
genotype-5-->genotype-1;
genotype-12-->genotype-13;