graph TD;
genotype-25-->root;
genotype-35-->root;
genotype-36-->genotype-35;
genotype-37-->root;
genotype-42-->genotype-36;
genotype-2-->root;
genotype-12-->genotype-25;
genotype-19-->genotype-12;
genotype-20-->root;
genotype-23-->genotype-12;
genotype-32-->genotype-12;
genotype-24-->root;
genotype-27-->genotype-2;
genotype-31-->genotype-12;
genotype-34-->root;
genotype-38-->root;
genotype-39-->genotype-34;
genotype-14-->genotype-12;
genotype-28-->genotype-14;
genotype-29-->genotype-12;
genotype-22-->root;
genotype-15-->genotype-22;
genotype-43-->genotype-22;
genotype-18-->genotype-12;
genotype-30-->genotype-14;
genotype-40-->genotype-12;
genotype-45-->genotype-40;
genotype-21-->genotype-45;
genotype-46-->genotype-30;
genotype-13-->genotype-12;
genotype-44-->genotype-21;
genotype-17-->genotype-44;
genotype-41-->genotype-40;
genotype-10-->genotype-25;
genotype-9-->genotype-10;
genotype-33-->genotype-35;
genotype-6-->genotype-35;
genotype-11-->genotype-6;
genotype-26-->genotype-35;
genotype-16-->genotype-10;
genotype-1-->genotype-2;
genotype-3-->genotype-2;
genotype-4-->genotype-2;
genotype-5-->genotype-2;
genotype-7-->genotype-2;
genotype-8-->genotype-2;